// Code generated by MockGen. DO NOT EDIT.
// Source: ./dependencytrack/dependencytrack.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDependencyTrackClient is a mock of DependencyTrackClient interface.
type MockDependencyTrackClient struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyTrackClientMockRecorder
}

// MockDependencyTrackClientMockRecorder is the mock recorder for MockDependencyTrackClient.
type MockDependencyTrackClientMockRecorder struct {
	mock *MockDependencyTrackClient
}

// NewMockDependencyTrackClient creates a new mock instance.
func NewMockDependencyTrackClient(ctrl *gomock.Controller) *MockDependencyTrackClient {
	mock := &MockDependencyTrackClient{ctrl: ctrl}
	mock.recorder = &MockDependencyTrackClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyTrackClient) EXPECT() *MockDependencyTrackClientMockRecorder {
	return m.recorder
}

// AddTagsToProject mocks base method.
func (m *MockDependencyTrackClient) AddTagsToProject(ctx context.Context, projectName, projectVersion string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagsToProject", ctx, projectName, projectVersion, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTagsToProject indicates an expected call of AddTagsToProject.
func (mr *MockDependencyTrackClientMockRecorder) AddTagsToProject(ctx, projectName, projectVersion, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagsToProject", reflect.TypeOf((*MockDependencyTrackClient)(nil).AddTagsToProject), ctx, projectName, projectVersion, tags)
}

// DeactivateProject mocks base method.
func (m *MockDependencyTrackClient) DeactivateProject(ctx context.Context, projectName, projectVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateProject", ctx, projectName, projectVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateProject indicates an expected call of DeactivateProject.
func (mr *MockDependencyTrackClientMockRecorder) DeactivateProject(ctx, projectName, projectVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateProject", reflect.TypeOf((*MockDependencyTrackClient)(nil).DeactivateProject), ctx, projectName, projectVersion)
}

// DeleteProject mocks base method.
func (m *MockDependencyTrackClient) DeleteProject(ctx context.Context, projectName, projectVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectName, projectVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockDependencyTrackClientMockRecorder) DeleteProject(ctx, projectName, projectVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockDependencyTrackClient)(nil).DeleteProject), ctx, projectName, projectVersion)
}

// UploadBOM mocks base method.
func (m *MockDependencyTrackClient) UploadBOM(ctx context.Context, projectName, projectVersion, parentName, parentVersion string, bom []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadBOM", ctx, projectName, projectVersion, parentName, parentVersion, bom)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadBOM indicates an expected call of UploadBOM.
func (mr *MockDependencyTrackClientMockRecorder) UploadBOM(ctx, projectName, projectVersion, parentName, parentVersion, bom interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBOM", reflect.TypeOf((*MockDependencyTrackClient)(nil).UploadBOM), ctx, projectName, projectVersion, parentName, parentVersion, bom)
}
