apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbomreport-to-dependencytrack.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sbomreport-to-dependencytrack.labels" . | nindent 4 }}
    {{- if .Values.deploymentLabels }}{{- toYaml .Values.deploymentLabels | nindent 4 }}{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sbomreport-to-dependencytrack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sbomreport-to-dependencytrack.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}{{- toYaml .Values.podLabels | nindent 8 }}{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sbomreport-to-dependencytrack"]
          args: ["server", "--port", "{{ .Values.service.port }}"]
          env:
            - name: DT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: {{ .Values.config.apiKeySecretName }}
            - name: DT_BASE_URL
              value: {{ .Values.config.baseUrl | quote }}
            - name: DT_PARENT_NAME
              value: {{ .Values.config.parentProjectName | quote }}
            - name: DT_PARENT_VERSION
              value: {{ .Values.config.parentProjectVersion | quote }}
            - name: DT_PROJECT_NAME
              value: {{ .Values.config.projectName | quote }}
            - name: DT_PROJECT_VERSION
              value: {{ .Values.config.projectVersion | quote }}
            - name: DT_PROJECT_TAGS
              value: {{ .Values.config.projectTags | quote }}
            {{- with .Values.config.dtrackClientTimeout }}
            - name: DT_DTRACK_CLIENT_TIMEOUT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.config.sbomUploadTimeoutSec }}
            - name: DT_SBOM_UPLOAD_TIMEOUT_SEC
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.config.sbomUploadCheckIntervalSec }}
            - name: DT_SBOM_UPLOAD_CHECK_INTERVAL_SEC
              value: {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
